### ISSUE TITLE
Minor documentation inconsistency

### ISSUE THREAD

**Issue by daanlenaerts** [uhppoted/uhppote-cli#8]
First of all, thank you very much for developing the uhppoted tools.

While trying out the uhppote-cli I noticed a minor inconsistency in the README.
It erroneously mentions the `broadcast` option twice for all commands, instead of the `listen`  option.

**Comment by uhppoted** [comment]
Glad you've found it useful !!

re. README. Clearly nobody (well, apart from you) reads the documentation :-) ... that's been there since the command descriptions were [first added](https://github.com/uhppoted/uhppote-cli/commit/9ebc66ae43cb103a98ed015ea7781ca31952b2fb) to the README.

Thanks for the heads up - will fix it!

**Comment by daanlenaerts** [comment]
It works really well, so definitely!

Yeah I guess not many people read manuals ;-)
I assume my network setup is a bit more involved, so I guess the default settings are fine for most people.
But thanks a lot, it could save the next person like me 10 minutes of confusion as to why listening is not working. :-)
